server:
  port: 8080
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/springboot_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true
      username: root
      password: <PASSWORD>
      driver-class-name: com.mysql.cj.jdbc.Driver
    elactricsearch:
      host: http://10.245.142.245
      port: 5601
      cluster-name: elasticsearch
      index-name: springboot_demo